export const visaTypes = [
  "Entry",
  "Tourist",
  "Pilgrimage",
  "Political",
  "Service",
  "Transit",
  "Press",
  "Family",
  "Business",
  "Relative visit",
  "Tourist (Urgent)",
  "Drivers",
];
export const passportTypes = [
  "Regular",
  "Service",
  "Travel Document",
  "Laissez-passer",
  "Official",
];
export const nationality = [
  "🇦🇫 Afghan",
  "🇮🇷 Iran",
  "🇮🇶 Iraq",
  "🇵🇰 Pakistan",
  "🇮🇳 India",
  "🇹🇷 Turkey",
  "🇸🇦 Saudi Arabia",
  "🇦🇪 United Arab Emirates",
  "🇹🇯 Tajikistan",
  "🇺🇿 Uzbekistan",
];
export const visaCenterLocation = [
  "Kabul",
  "Herat",
  "Mazar-i-Sharif",
  "Kandahar",
  "Jalalabad",
];

export const gender = ["Male", "Female"];
export const maritalStatus = ["Single", "Married", "Widowed", "Divorced"];
export const stayPeriod = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "80",
  "81",
  "82",
  "83",
  "84",
  "85",
  "86",
  "87",
  "88",
  "89",
  "90",
];

export const entryType = ["Single entry", "Double entry", "Multiple entry"];
export const jobTitles = [
  "Web developer",
  "Software engineer",
  "Project manager",
  "Information systems specialist",
  "Network engineer",
  "IT manager",
  "UI/UX designer",
  "Information security specialist",
  "Network administrator",
  "Database specialist",
  "Communications specialist",
  "Software developer",
  "Systems analyst",
  "Database manager",
  "Hardware engineer",
  "CRM specialist",
  "ERP specialist",
  "Technology operations manager",
  "Technical support specialist",
  "Mobile app specialist",
  "Game developer",
  "Communications engineer",
  "Information systems manager",
  "Website developer",
  "Health informatics specialist",
  "Data analyst",
  "Cryptography engineer",
  "Telecommunications specialist",
  "Information security manager",
  "Computer engineer",
  "Web application developer",
  "Network specialist",
  "Mobile game developer",
  "Optical communications specialist",
  "Technical support lead",
  "Database administrator",
  "Computer engineer",
  "Network security specialist",
  "Information systems analyst",
  "Server specialist",
  "Cybersecurity manager",
  "Mobile app developer",
  "Wireless communications specialist",
  "Digital manager",
  "Web design specialist",
  "Online game developer",
];

export const birthLocations = [
  "Kabul",
  "Herat",
  "Mazar-i-Sharif",
  "Kandahar",
  "Balkh",
  "Baghlan",
  "Pul-e-Khumri",
  "Nangarhar",
  "Faryab",
  "Ghazni",
  "Paktia",
  "Kunar",
  "Zabul",
  "Bamyan",
  "Laghman",
  "Panjshir",
  "Nimruz",
  "Helmand",
  "Badghis",
  "Kapisa",
  "Samangan",
  "Khost",
  "Badakhshan",
  "Jowzjan",
  "Sar-e Pol",
  "Daykundi",
  "Takhar",
  "Farah",
  "Nuristan",
  "Baghdad",
];

export const instructions = [
  {
    id: 100,
    step: "Step 1",
    title: "Personal information",
    content: [
      `If you hold dual nationality, please select the passport nationality that you plan to use for travel to Iran.`,
      `If the nationality on the visa does not match the nationality on the passport, the visa may be invalid.`,
      `A valid passport with at least six months of remaining validity is required for visa processing.`,
      `Please upload a passport photo that meets the guidelines. Follow the passport photo standards.`,
      `Please upload a scan of the passport data page according to the standards. Follow the passport scan guidelines.`,
    ],
  },
  {
    id: 200,
    step: "Step 2",
    title: "Contact information",
    content: [
      `Please enter your name exactly as it appears on your passport or travel document, even if it differs from other identification documents.`,
      `Please enter your family name exactly as it appears on your passport or travel document, even if it differs from the name on your passport.`,
      `If you have a middle name on your passport, include it after your given name in the first name field.`,
      `Please enter your contact information carefully. This information will be used to review your application. Incorrect details may lead to rejection.`,
      `At the end of the application process, a confirmation email will be sent to the email address you provide. Contact us if you do not receive it.`,
      `All correspondence is sent to your email address, so please enter it accurately.`,
      `You must complete email verification after submitting your application.`,
      `Please provide your residence address in Iran precisely.`,
    ],
  },
  {
    id: 300,
    step: "Step 3",
    title: "Passport information",
    content: [
      `Please enter your passport details carefully. Visas are issued based on your passport information, and any mismatch may invalidate the visa.`,
      `Passport scans must be in JPG format and under 500KB.`,
      `A valid passport with at least six months of remaining validity is required for visa processing.`,
    ],
  },
  {
    id: 400,
    step: "Step 4",
    title: "Visa information",
    content: [
      `Please select the visa processing center from the list of Iranian foreign ministry offices. This is the location where you will submit documents or receive your visa.`,
      `Visa duration and entry type may change during the review process.`,
    ],
  },
  {
    id: 500,
    title: "Important notes before applying",
    content: [
      `If you hold dual nationality, please select the passport nationality that you plan to use for travel to Iran.`,
      `If the nationality on the visa does not match the nationality on the passport, the visa may be invalid.`,
      `A valid passport with at least six months of remaining validity is required for visa processing.`,
      `Please upload a passport photo that meets the guidelines. Follow the passport photo standards.`,
      `Please upload a scan of the passport data page according to the standards. Follow the passport scan guidelines.`,
    ],
  },
];

export const formProgressSteps = [
  { id: "requirements", title: "Visa eligibility check" },
  ...instructions
    .filter((item) => [100, 200, 300, 400].includes(item.id))
    .map((item) => ({
      id: item.id,
      title: item.title,
    })),
];

export const formFields = [
  {
    id: 1,
    type: "InputField",
    props: {
      name: "visaType",
      type: "text",
      label: "Visa type",
      options: visaTypes,
      required: true,
    },
  },
  {
    id: 2,
    type: "InputField",
    props: {
      name: "nationality",
      type: "text",
      label: "Nationality",
      options: nationality,
      required: true,
    },
  },
  {
    id: 3,
    type: "InputField",
    props: {
      name: "passportType",
      type: "text",
      label: "Passport type",
      options: passportTypes,
      required: true,
    },
  },
  {
    id: 4,
    type: "InputField",
    props: {
      name: "visaCenterLocation",
      type: "text",
      label: "Visa center location",
      options: visaCenterLocation,
      instruction:
        "The embassy or consulate where you plan to submit documents or receive your visa.",
      required: true,
    },
  },
  {
    id: 5,
    type: "InputField",
    props: {
      name: "nationalityDuplicate",
      type: "text",
      label: "Nationality duplicate",
      options: nationality,
      required: true,
    },
  },
  {
    id: 6,
    type: "InputField",
    props: {
      name: "visaTypeDuplicate",
      type: "text",
      label: "Visa type duplicate",
      options: visaTypes,
      required: true,
    },
  },
  {
    id: 7,
    type: "InputField",
    props: {
      name: "firstName",
      type: "text",
      label: "First name",
      required: true,
    },
  },
  {
    id: 8,
    type: "InputField",
    props: {
      name: "lastName",
      type: "text",
      label: "Last name",
      required: true,
    },
  },
  {
    id: 9,
    type: "InputField",
    props: {
      name: "fatherName",
      type: "text",
      label: "Father's name",
      required: true,
    },
  },
  {
    id: 10,
    type: "InputField",
    props: {
      name: "gender",
      type: "text",
      label: "Gender",
      options: gender,
      required: true,
    },
  },
  {
    id: 11,
    type: "InputField",
    props: {
      name: "previousNationality",
      type: "text",
      label: "Previous nationality",
      options: nationality,
      required: true,
    },
  },
  {
    id: 12,
    type: "InputField",
    props: {
      name: "birthLocation",
      type: "text",
      label: "Birth place",
      options: birthLocations,
      required: true,
    },
  },
  {
    id: 13,
    type: "CustomDatePicker",
    props: {
      name: "birthDate",
      label: "Birth date",
      required: "true",
    },
  },
  {
    id: 14,
    type: "InputField",
    props: {
      name: "maritalStatus",
      type: "radio-group",
      label: "Marital status",
      options: maritalStatus,
      required: true,
    },
  },
  {
    id: 15,
    type: "InputField",
    props: {
      name: "jobTitle",
      type: "text",
      label: "Job title",
      options: jobTitles,
      required: true,
    },
  },
  {
    id: 16,
    type: "CustomDropzone",
    props: {
      name: "personalPhoto",
      required: true,
    },
    label: "Personal photo",
  },
  {
    id: 17,
    type: "InputField",
    props: {
      name: "applicantPhoneNumber",
      type: "tel",
      label: "Applicant phone number",
      required: true,
    },
  },
  {
    id: 18,
    type: "InputField",
    props: {
      name: "applicantMobileNumber",
      type: "tel",
      label: "Applicant mobile number",
      required: true,
    },
  },
  {
    id: 19,
    type: "InputField",
    props: {
      name: "email",
      type: "email",
      label: "Email",
      required: true,
    },
  },
  {
    id: 20,
    type: "InputField",
    props: {
      name: "postalCode",
      type: "text",
      label: "Postal code",
      required: false,
    },
  },
  {
    id: 21,
    type: "InputField",
    props: {
      name: "residenceAddress",
      type: "textarea",
      label: "Residence address",
      required: true,
    },
  },
  {
    id: 22,
    type: "InputField",
    props: {
      name: "phoneNumberInIran",
      type: "tel",
      label: "Phone number in Iran",
      required: true,
    },
  },
  {
    id: 23,
    type: "InputField",
    props: {
      name: "addressInIran",
      type: "textarea",
      label: "Address in Iran",
      required: true,
    },
  },
  {
    id: 24,
    type: "InputField",
    props: {
      name: "passportNumber",
      type: "number",
      label: "Passport number",
      required: true,
    },
  },
  {
    id: 25,
    type: "InputField",
    props: {
      name: "passportTypeDuplicate",
      type: "text",
      label: "Passport type duplicate",
      options: passportTypes,
      required: true,
    },
  },
  {
    id: 26,
    type: "CustomDatePicker",
    props: {
      name: "issueDate",
      label: "Issue date",
      required: "true",
    },
  },
  {
    id: 27,
    type: "CustomDatePicker",
    props: {
      name: "expirationDate",
      label: "Expiration date",
      required: "true",
    },
  },
  {
    id: 28,
    type: "CustomDropzone",
    props: {
      name: "passportPhoto",
      required: true,
    },
    label: "Passport photo",
  },
  {
    id: 29,
    type: "InputField",
    props: {
      name: "stayPeriod",
      type: "number",
      label: "Length of stay (days)",
      options: stayPeriod,
      required: true,
    },
  },
  {
    id: 30,
    type: "InputField",
    props: {
      name: "entryType",
      type: "text",
      label: "Entry type",
      options: entryType,
      required: true,
    },
  },
  {
    id: 31,
    type: "InputField",
    props: {
      name: "urgentRequest",
      type: "checkbox",
      label: "Urgent request",
      instruction: "If selected, urgent processing adds 50% to the visa fee.",
      required: false,
    },
  },
  {
    id: 32,
    type: "CustomDropzone",
    props: {
      name: "passportStampPhoto",
      required: false,
    },
    label: "Passport stamp extension photo",
  },
  {
    id: 33,
    type: "CustomDropzone",
    props: {
      name: "residenceCard",
      required: false,
    },
    label: "Residence card",
  },
  {
    id: 34,
    type: "CustomDropzone",
    props: {
      name: "backOfResidenceCardPhoto",
      required: false,
    },
    label: "Back of residence card photo",
  },
  {
    id: 35,
    type: "CustomDatePicker",
    props: {
      name: "approximateEntryDate",
      label: "Approximate entry date",
      required: "true",
    },
  },
  {
    id: 36,
    type: "CustomDatePicker",
    props: {
      name: "approximateExitDate",
      label: "Approximate exit date",
      required: "true",
    },
  },
  {
    id: 37,
    type: "CustomDropzone",
    props: {
      name: "residenceCardIfNecessary",
      required: false,
    },
    label: "Residence card if required",
  },
  {
    id: 38,
    type: "InputField",
    props: {
      type: "textarea",
      name: "travelPurpose",
      label: "Purpose of visit",
      required: true,
    },
  },
  {
    id: 39,
    type: "InputField",
    props: {
      type: "textarea",
      name: "visaCost",
      label: "Visa cost",
      cost: "visaType",
    },
  },
];
