export const initialState = {
  user: {
    isAuthenticated: false,
    details: null,
    loading: false,
    error: null,
  },
  step: 1,
  formData: {
    visaType: '',
    nationality: 'افغان',
    passportType: '',
    visaCenterLocation: '',
    nationalityDuplicate: '',
    visaTypeDuplicate: '',
    firstName: '',
    lastName: '',
    fatherName: '',
    gender: '',
    previousNationality: '',
    currentNationality: '',
    birthLocation: '',
    birthDate: null,
    maritalStatus: '',
    jobTitle: '',
    photo: '',
    applicantPhoneNumber: '',
    applicantMobileNumber: '',
    email: '',
    postalCode: '',
    residenceAddress: '',
    iranPhoneNumber: '',
    iranAddress: '',
    passportNumber: '',
    passportTypeDuplicate: '',
    issueDate: null,
    expirationDate: null,
    stayPeriod: '',
    entryType: '',
    urgentRequest: false,
    approximateEntryDate: null,
    approximateExitDate: null,
    travelPurpose: '',
    visaCost: [100, 200, 300, 400, 500, 600, 700, 250],
  },
  submissionStatus: {
    isSubmitting: false,
    success: null,
    error: null,
  },
  ui: {
    theme: 'light',
  },
};
